use crate::model::MakefileDoc;

pub fn generate(doc: &MakefileDoc) -> String {
    let mut md = String::new();

    md.push_str("# Makefile Documentation\n");
    md.push_str(concat!(
        "> *Auto-generated by [makefile2doc](",
        env!("CARGO_PKG_REPOSITORY"),
        ")*\n\n"
    ));
    md.push_str(&generate_cheat_sheet(doc));

    md.push_str("\n---\n\n");

    md.push_str(&generate_workflow_graph(doc));

    md.push_str("\n---\n\n");

    md.push_str(&generate_section_details(doc));
    md
}

fn generate_cheat_sheet(doc: &MakefileDoc) -> String {
    let mut section = String::new();

    section.push_str("## Cheat Sheet\n");
    section.push_str("| Command | Category | Description |\n");
    section.push_str("| :--- | :--- | :--- |\n");

    for cat in &doc.categories {
        for cmd in &cat.commands {
            let anchor = slugify(&cat.name);
            let desc = cmd.description.replace("\\n", "<br>");
            section.push_str(&format!(
                "| [`make {}`](#{}) | {} | {} |\n",
                cmd.name, anchor, cat.name, desc
            ));
        }
    }
    section
}

fn generate_workflow_graph(doc: &MakefileDoc) -> String {
    let mut section = String::new();
    section.push_str("## Workflow Graph\n");
    section.push_str("```mermaid\n");
    section.push_str("flowchart LR\n");

    for (i, cat) in doc.categories.iter().enumerate() {
        let safe_cat_name = cat.name.replace(" ", "_");

        section.push_str(&format!("    subgraph {}[{}]\n", safe_cat_name, cat.name));

        for cmd in &cat.commands {
            section.push_str(&format!("        {}({})\n", cmd.name, cmd.name));
        }

        section.push_str("    end\n");

        section.push_str(&format!(
            "    style {} fill:transparent,stroke-dasharray: 5 5\n",
            safe_cat_name
        ));

        let colors = [
            "#E1F5FE", "#E8F5E9", "#FFF3E0", "#F3E5F5", "#FFEBEE", "#ECEFF1",
        ];
        let stroke_colors = [
            "#01579B", "#1B5E20", "#E65100", "#4A148C", "#B71C1C", "#263238",
        ];
        let color_idx = i % colors.len();

        section.push_str(&format!(
            "    classDef cat{} fill:{},stroke:{},stroke-width:2px,color:#000;\n",
            i, colors[color_idx], stroke_colors[color_idx]
        ));

        for cmd in &cat.commands {
            section.push_str(&format!("    class {} cat{}\n", cmd.name, i));
        }
    }

    section.push_str("\n");
    for cat in &doc.categories {
        for cmd in &cat.commands {
            for dep in &cmd.dependencies {
                section.push_str(&format!("    {} --> {}\n", cmd.name, dep));
            }
        }
    }

    section.push_str("```\n");
    section
}

fn generate_section_details(doc: &MakefileDoc) -> String {
    let mut section = String::new();

    section.push_str("## Section Details\n");

    for cat in &doc.categories {
        section.push_str(&format!("\n### {}\n", cat.name));
        section.push_str("| Command | Description | Dependencies | Required Variables |\n");
        section.push_str("| :--- | :--- | :--- | :--- |\n");

        for cmd in &cat.commands {
            let desc = format_description(&cmd.description);
            let deps = format_list(&cmd.dependencies);
            let envs = format_list(&cmd.env);

            section.push_str(&format!(
                "| `make {}` | {} | {} | {} |\n",
                cmd.name, desc, deps, envs
            ));
        }
    }

    section
}

fn format_description(desc: &str) -> String {
    if desc.is_empty() {
        "-".to_string()
    } else {
        desc.replace("\\n", "<br>")
    }
}

fn format_list(items: &[String]) -> String {
    if items.is_empty() {
        "-".to_string()
    } else {
        items
            .iter()
            .map(|i| format!("`{}`", i))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn slugify(text: &str) -> String {
    text.trim()
        .to_lowercase()
        .chars()
        .map(|c| if c.is_whitespace() { '-' } else { c })
        .filter(|c| c.is_alphanumeric() || *c == '-')
        .collect()
}
